# Base image
FROM node:18-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copia os arquivos de dependências para o diretório de trabalho
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia o código do projeto para o diretório de trabalho
COPY . .

# Expõe a porta onde o aplicativo estará em execução (geralmente porta 3000 para projetos Next.js)
EXPOSE 3000

# Comando padrão para iniciar o servidor de desenvolvimento do Next.js
CMD ["npm", "run", "dev"]
