# Usa uma imagem base do Node.js
FROM node:18-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copia o arquivo package.json e package-lock.json para o diretório de trabalho
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia o restante do código fonte para o diretório de trabalho
COPY . .

# Expõe a porta 8080
EXPOSE 4000

# Comando para iniciar o servidor Node.js
CMD [ "npm", "run", "dev" ]
